name: CI Tests
on:
  pull_request:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go-version:
              - "1.22"
              - "1.23"

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: 1.2.11
        
        - name: Set up Golang ${{ matrix.go-version }}
          uses: actions/setup-go@v5
          with:
           go-version: ${{ matrix.go-version }}
  
        - name: Install dependencies
          run: bun install
        
        - name: Run tests
          run: bun run test